# This is for "server" based databases only, ignore this if you are using a local file
# Runs a local postgresql database, make sure POSTGRES_URL in .env matches credentials
# e.g. postgresql://postgres:password@localhost:5432/osulive

# Pre-installation command:
# docker pull postgres

docker run --name postgres-container \
-e POSTGRES_USER=postgres \
-e POSTGRES_PASSWORD=password \
-e POSTGRES_DB=osulive \
-d -p 5432:5432 postgres